interface IInputRekapPadam {
  no_apkt: string,
  jam_padam: string,  // 2022-08-26T08:39:45.259Z
  id_ref_indikasi: string,  //Ref Ep Indikasi API
  beban_padam: string,
  penyebab: string,
  jenis_padam: string,
  r: string,
  s: string,
  t: string,
  n: string,
  fai_arus_ggn_hmi: string,
  keterangan: string,
  lbs_manual: string,
  jenis_peralatan: string,
  id_keypoint: string, // peralatan - belum pasti
  id_up3: string,
  id_ulp: string,
  jlh_gardu_padam: string,
  pelanggan_tm: string,
  pelanggan_vip: string,
  nama_lokasi: string,
  wilayah_padam: string, // from alamat ref lokasi
  id_ref_ep_cuaca: string, // Ref ep cuaca
}

export const EditRekapPadamField = {
  "nama_lokasi": "",
  "id_keypoint": "",
  "id_ref_ep_indikasi": "",
  "id_ref_ep_penyebab_ggn": "",
  "id_ref_ep_cuaca": "",
  "id_up3": "",
  "id_ulp": "",
  "id_penyulang_fdir": "",
  "id_user_update": "",
  "no_apkt": "",
  "penyebab": "",
  "jenis_padam": "",
  "r": "",
  "s": "",
  "t": "",
  "n": "",
  "beban_padam": "",
  "indikator_kerja": "",
  "jenis_pemeliharaan": "",
  "gangguan_ditemukan": "",
  "keterangan_ggn": "",
  "status_penyulang_fdir": "",
  "keterangan_penyulang_fdir": "",
  "aco_kerja": "",
  "jam_padam": "",
  "jam_buka": "",
  "jam_tutup": "",
  "jam_trip": "",
  "jam_normal": "",
  "jml_ggn_tahun": "",
  "jml_ggn_bulan": "",
  "posting": "",
  "keterangan": "",
  "lbs_manual": "",
  "jenis_keypoint": "",
  "sepatetik_trip": "",
  "koordinasi_proteksi": "",
  "gagal_ar": "",
  "keterangan_proteksi": "",
  "id_ref_ep_ag_hmi": null,
  "id_ref_ep_kat_ggn": null,
  "id_status_proteksi": null,
  "id_ref_ep_petugas_1": null,
  "id_ref_ep_petugas_2": null,
  "id_ref_ep_petugas_3": null,
  "keterangan_anev": null,
  "anev": null,
  gangguan_padam: ""
};

interface IUpdateRekapPadam {
  "id_trans_ep": number,
  "id_keypoint": number,
  "id_ref_ep_indikasi": number,
  "id_ref_ep_penyebab_ggn": number,
  "id_ref_ep_cuaca": number,
  "id_up3": number,
  "id_ulp": number,
  "id_penyulang_fdir": any,
  "id_user_update": number,
  "no_apkt": any,
  "penyebab": string,
  "jenis_padam": string,
  "nama_lokasi": string,
  "r": number,
  "s": number,
  "t": number,
  "n": number,
  "beban_padam": number,
  "indikator_kerja": string,
  "jenis_pemeliharaan": string,
  "gangguan_ditemukan": string,
  "keterangan_ggn": string,
  "status_penyulang_fdir": any,
  "keterangan_penyulang_fdir": any,
  "aco_kerja": any,
  "jam_padam": any,
  "jam_buka": any,
  "jam_tutup": any,
  "jam_trip": any,
  "jam_normal": any,
  "jml_ggn_tahun": number,
  "jml_ggn_bulan": number,
  "posting": boolean,
  "keterangan": string,
  "lbs_manual": string,
  "jenis_keypoint": string,
  "sepatetik_trip": string,
  "koordinasi_proteksi": string,
  "gagal_ar": string,
  "keterangan_proteksi": string,
  "id_ref_ep_ag_hmi": number,
  "id_ref_ep_kat_ggn": number,
  "id_status_proteksi": number,
  "id_ref_ep_petugas_1": number,
  "id_ref_ep_petugas_2": number,
  "id_ref_ep_petugas_3": number,
}

export type { IInputRekapPadam, IUpdateRekapPadam };