export const MANAGEMENT_UPLOADS_JQX = () => {
  return {
    datafields: [
      { name: 'number', type: 'number' },
      { name: 'id', type: 'number' },
      { name: 'event_upload', type: 'string' },
      { name: 'validasi', type: 'number' },
      { name: 'id_ref_lokasi', type: 'number' },
      { name: 'nama_lokasi', type: 'string' },
      { name: 'kode_lokasi', type: 'string' },
      { name: 'id_parent_lokasi', type: 'number' },
      { name: 'id_ref_jenis_lokasi', type: 'number' },
      { name: 'id_uid', type: 'number' },
      { name: 'id_up2b', type: 'number' },
      { name: 'id_up2d', type: 'number' },
      { name: 'id_up3b', type: 'number' },
      { name: 'id_up3_1', type: 'number' },
      { name: 'id_up3_2', type: 'number' },
      { name: 'id_ulp_1', type: 'number' },
      { name: 'id_ulp_2', type: 'number' },
      { name: 'id_upt', type: 'number' },
      { name: 'id_ultg', type: 'number' },
      { name: 'sub_sistem', type: 'number' },
      { name: 'id_unit_pembangkit', type: 'number' },
      { name: 'id_pembangkit', type: 'number' },
      { name: 'id_ref_jenis_pembangkit', type: 'number' },
      { name: 'id_gardu_induk', type: 'number' },
      { name: 'id_trafo_gi', type: 'number' },
      { name: 'id_penyulang', type: 'number' },
      { name: 'id_gardu_hubung', type: 'number' },
      { name: 'id_zone', type: 'number' },
      { name: 'id_section', type: 'number' },
      { name: 'id_segment', type: 'number' },
      { name: 'id_gardu_distribusi', type: 'number' },
      { name: 'id_trafo_gd', type: 'number' },
      { name: 'parent_lokasi', type: 'string' },
      { name: 'ref_jenis_lokasi', type: 'string' },
      { name: 'uid', type: 'string' },
      { name: 'up2b', type: 'string' },
      { name: 'up2d', type: 'string' },
      { name: 'up3b', type: 'string' },
      { name: 'up3_1', type: 'string' },
      { name: 'up3_2', type: 'string' },
      { name: 'ulp_1', type: 'string' },
      { name: 'ulp_2', type: 'string' },
      { name: 'upt', type: 'string' },
      { name: 'ultg', type: 'string' },
      { name: 'subsistem', type: 'string' },
      { name: 'unit_pembangkit', type: 'string' },
      { name: 'pembangkit', type: 'string' },
      { name: 'ref_jenis_pembangkit', type: 'string' },
      { name: 'gardu_induk', type: 'string' },
      { name: 'trafo_gi', type: 'string' },
      { name: 'penyulang', type: 'string' },
      { name: 'gardu_hubung', type: 'string' },
      { name: 'zone', type: 'string' },
      { name: 'section', type: 'string' },
      { name: 'segment', type: 'string' },
      { name: 'gardu_distribusi', type: 'string' },
      { name: 'trafo_gd', type: 'string' },
      { name: 'id_ref_province', type: 'number' },
      { name: 'id_ref_regency', type: 'number' },
      { name: 'id_ref_district', type: 'number' },
      { name: 'id_user_entri', type: 'number' },
      { name: 'id_user_update', type: 'number' },
      { name: 'tgl_entri', type: 'string' },
      { name: 'tgl_update', type: 'string' },
      { name: 'status_listrik', type: 'number' },
      { name: 'tree_jaringan', type: 'number' },
      { name: 'fungsi_lokasi', type: 'string' },
      { name: 'no_tiang', type: 'string' },
      { name: 'zona', type: 'string' },
      { name: 'alamat', type: 'string' },
      { name: 'coverage', type: 'string' },
      { name: 'kva', type: 'number' },
      { name: 'phase', type: 'string' },
      { name: 'lat', type: 'number' },
      { name: 'lon', type: 'number' },
      { name: 'status_penyulang', type: 'string' },
      { name: 'no_urut', type: 'number' },
      { name: 'fungsi_scada', type: 'string' },
      { name: 'kapasitas', type: 'number' },
      { name: 'pemilik', type: 'string' },
      { name: 'status_trafo', type: 'string' },
      { name: 'ratio_ct', type: 'number' },
      { name: 'ratio_vt', type: 'number' },
      { name: 'fk_meter_pembanding', type: 'number' },
      { name: 'primer_tegangan_max', type: 'number' },
      { name: 'primer_tegangan_min', type: 'number' },
      { name: 'sekunder_tegangan_min', type: 'number' },
      { name: 'sekunder_tegangan_max', type: 'number' },
      { name: 'jenis_layanan', type: 'string' },
      { name: 'jenis_gi', type: 'string' },
      { name: 'jenis_peralatan', type: 'string' },
      { name: 'jenis_gardu', type: 'string' },
      { name: 'jenis_jaringan', type: 'string' },
      { name: 'jenis_trafo', type: 'string' },
      { name: 'sinkron_data', type: 'string' },
      { name: 'path1', type: 'string' },
      { name: 'path2', type: 'string' },
      { name: 'path3', type: 'string' },
      { name: 'id_i', type: 'number' },
      { name: 'id_v', type: 'number' },
      { name: 'id_p', type: 'number' },
      { name: 'id_amr', type: 'number' },
      { name: 'id_portal_ext', type: 'number' },
      { name: 'url_webservice', type: 'string' },
      { name: 'rekon_beban', type: 'number' },
      { name: 'i_max', type: 'number' },
      { name: 'faktor_meter', type: 'number' },
      { name: 'faktor_kali', type: 'number' },
      { name: 'dcc', type: 'string' },
      { name: 'def_pengukuran_teg_primer', type: 'string' },
      { name: 'def_pengukuran_teg_sekunder', type: 'string' },
      { name: 'def_nilai_cosq', type: 'string' },
      { name: 'ufr', type: 'number' },
      { name: 'jumlah_jurusan', type: 'number' },
      { name: 'jumlah_pelanggan', type: 'number' },
      { name: 'pelanggan_tm', type: 'number' },
      { name: 'pelanggan_vip', type: 'number' },
      { name: 'panjang_jaringan', type: 'number' },
      { name: 'id_ref_fungsi_lokasi', type: 'number' },
      { name: 'nama_eam', type: 'string' },

    ],
    columngroups: [
      { text: 'Mapping SCADA', align: 'center', name: 'mappingscada' },
      { text: 'Mapping AMR', align: 'center', name: 'mappingamr' },
      { text: 'Mapping Portal External', align: 'center', name: 'mappingportalex' },
    ],
    columns: [
      { text: 'NO', datafield: 'number', width: 50, sortable: false },
      { text: 'NAMA', datafield: 'nama_lokasi', width: 200, },
      { text: 'KODE', datafield: 'kode_lokasi', width: 200, },
      { text: 'NO TIANG', datafield: 'no_tiang', width: 100, checked: true },

      // { text: 'TRAFO GD', datafield: 'trafo_gd', width: 200, },
      { text: 'GARDU DISTRIBUSI', datafield: 'gardu_distribusi', width: 200, },
      { text: 'SEGMENT', datafield: 'segment', width: 200, },
      { text: 'SECTION', datafield: 'section', width: 200, },
      { text: 'ZONE', datafield: 'zone', width: 200, },
      { text: 'GARDU HUBUNG', datafield: 'gardu_hubung', width: 200, },
      { text: 'PENYULANG', datafield: 'penyulang', width: 200, },
      { text: 'TRAFO GI', datafield: 'trafo_gi', width: 200, },
      { text: 'SUBSISTEM', datafield: 'subsistem', width: 200, },
      { text: 'GARDU INDUK', datafield: 'gardu_induk', width: 200, },
      { text: 'PEMBANGKIT', datafield: 'pembangkit', width: 200, },
      { text: 'JENIS PEMBANGKIT', datafield: 'ref_jenis_pembangkit', width: 200, },
      { text: 'UNIT PEMBANGKIT', datafield: 'unit_pembangkit', width: 200, },
      { text: 'UPT', datafield: 'upt', width: 200, },
      { text: 'ULTG', datafield: 'ultg', width: 200, },
      { text: 'ULP', datafield: 'ulp', width: 200, },
      { text: 'UP3', datafield: 'up3', width: 200, },
      { text: 'UP3B', datafield: 'up3b', width: 200, },
      { text: 'UP2D', datafield: 'up2d', width: 200, },
      { text: 'UP2B', datafield: 'up2b', width: 200, },
      { text: 'UNIT INDUK', datafield: 'unit_induk', width: 200, },

      { text: 'Fungsi Lokasi', datafield: 'fungsi_lokasi', width: 120, },
      { text: 'Zona', datafield: 'zona', width: 100, checked: true },
      { text: 'Alamat', datafield: 'alamat', width: 600, sortable: false },
      { text: 'Coverage', datafield: 'coverage', width: 300, sortable: false },
      { text: 'Latitude', datafield: 'lat', width: 100, checked: true },
      { text: 'Longitude', datafield: 'lon', width: 100, checked: true },
      { text: 'Total Pelanggan', datafield: 'jumlah_pelanggan', width: 120, },
      { text: 'Pelanggan VIP', datafield: 'pelanggan_vip', width: 100, },
      { text: 'Panjang Jaringan', datafield: 'panjang_jaringan', width: 120, },
      { text: 'Jenis Jaringan', datafield: 'jenis_jaringan', width: 200, },
      { text: 'Jenis Peralatan', datafield: 'jenis_peralatan', width: 200, },
      { text: 'Jenis Trafo', datafield: 'jenis_trafo', width: 200, },
      { text: 'Status Penyulang', datafield: 'status_penyulang', width: 120, },
      { text: 'Jumlah Gardu', datafield: 'count_gardu', width: 120, },
      { text: 'Kapasitas (MVA)', datafield: 'kapasitas', width: 120, },
      { text: 'Total Daya (kVA)', datafield: 'kva', width: 120, },
      { text: 'I Max (A)', datafield: 'i_max', width: 80, },
      { text: 'Teg. Primer (kV)', datafield: 'def_pengukuran_teg_primer', width: 125, },
      { text: 'Teg. Sekunder (kV)', datafield: 'def_pengukuran_teg_sekunder', width: 130, },
      { text: 'COS PHI', datafield: 'def_nilai_cosq', width: 80, },
      { text: 'Ratio CT', datafield: 'ratio_ct', width: 80, },
      { text: 'Ratio VT', datafield: 'ratio_vt', width: 80, },
      { text: 'FX Meter', datafield: 'fk_meter_pembanding', width: 80, },
      { text: 'Phase', datafield: 'phase', width: 200, },
      { text: 'DCC', datafield: 'dcc', width: 200, },
      { text: 'Pemilik', datafield: 'pemilik', width: 200, },
      { text: 'Fungsi SCADA', datafield: 'fungsi_scada', width: 200, },
      { text: 'Jenis GI', datafield: 'jenis_gi', width: 200, },
      { text: 'Jenis Gardu', datafield: 'jenis_gardu', width: 200, },
      { text: 'Jenis Layanan', datafield: 'jenis_layanan', width: 200, },

      { text: 'PATH1', columngroup: 'mappingscada', datafield: 'path1', width: 150, },
      { text: 'PATH2', columngroup: 'mappingscada', datafield: 'path2', width: 150, },
      { text: 'PATH3', columngroup: 'mappingscada', datafield: 'path3', width: 150, },
      { text: 'ID I(Arus)', columngroup: 'mappingscada', datafield: 'id_i', width: 150, },
      { text: 'ID V(Tegangan)', columngroup: 'mappingscada', datafield: 'id_v', width: 150, },
      { text: 'ID P(Daya)', columngroup: 'mappingscada', datafield: 'id_p', width: 150, },
      { text: 'ID AMR', columngroup: 'mappingamr', datafield: 'id_amr', width: 150, },
      { text: 'ID Portal EXT', columngroup: 'mappingportalex', datafield: 'id_portal_ext', width: 150, },
      { text: 'URL WebService', columngroup: 'mappingportalex', datafield: 'url_webservice', width: 150, },

      { text: 'Rekon Beban', datafield: 'rekon_beban', width: 100, columntype: 'checkbox', filtertype: 'bool' },
      { text: 'Status', datafield: 'status_listrik', width: 80, columntype: 'checkbox', filtertype: 'bool' },
      { text: 'Event Upload', datafield: 'event_upload', width: 100, },

    ]
  }
};