export const JENIS_LOKASI = () => {
  return {
    unit_pembangkit: 1,
    pembangkit: 2,
    uid: 3,
    gardu_induk: 4,
    trafo_gi: 5,
    penyulang: 6,
    zone: 7,
    section: 8,
    segment: 9,
    gardu_distribusi: 10,
    gardu_hubung: 11,
    trafo_gd: 14,
    up3: 15,
    ulp: 16,
    uiw: 17,
    up2d: 18,
    upt: 22,
    ultg: 23,
    up3b: 24,
    up2b: 25,
    subsistem: 26,
    recloser: 31,
    lbs: 32,
    sso: 33,
    fiohl: 34,
    evm: 35,
    keypoint: 36,
  }
};
