export const DEMO_TREE = [
  {
    aset: 'clocks',
    jenis: 'trip',
    kode: 13,
    tiang_gardist: 38,
    alamat: 8,
    coverage: 'single',
    subRows: [
      {
        aset: 'nerve',
        jenis: 'tin',
        kode: 3,
        tiang_gardist: 39,
        alamat: 78,
        coverage: 'single',
        subRows: [
          {
            aset: 'slope',
            jenis: 'dad',
            kode: 21,
            tiang_gardist: 10,
            alamat: 54,
            coverage: 'single',
          },
          {
            aset: 'mud',
            jenis: 'intention',
            kode: 27,
            tiang_gardist: 8,
            alamat: 19,
            coverage: 'single',
          },
          {
            aset: 'pot',
            jenis: 'part',
            kode: 18,
            tiang_gardist: 11,
            alamat: 26,
            coverage: 'relationship',
          },
          {
            aset: 'fork',
            jenis: 'rings',
            kode: 28,
            tiang_gardist: 8,
            alamat: 57,
            coverage: 'relationship',
          },
          {
            aset: 'need',
            jenis: 'arch',
            kode: 1,
            tiang_gardist: 58,
            alamat: 62,
            coverage: 'complicated',
          },
        ],
      },
      {
        aset: 'news',
        jenis: 'geese',
        kode: 3,
        tiang_gardist: 93,
        alamat: 22,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'grocery',
            jenis: 'glass',
            kode: 7,
            tiang_gardist: 57,
            alamat: 71,
            coverage: 'complicated',
          },
          {
            aset: 'question',
            jenis: 'thought',
            kode: 15,
            tiang_gardist: 66,
            alamat: 78,
            coverage: 'complicated',
          },
          {
            aset: 'resolution',
            jenis: 'bed',
            kode: 26,
            tiang_gardist: 20,
            alamat: 43,
            coverage: 'single',
          },
          {
            aset: 'republic',
            jenis: 'push',
            kode: 14,
            tiang_gardist: 79,
            alamat: 81,
            coverage: 'complicated',
          },
          {
            aset: 'bone',
            jenis: 'communication',
            kode: 8,
            tiang_gardist: 46,
            alamat: 58,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'depression',
        jenis: 'houses',
        kode: 23,
        tiang_gardist: 13,
        alamat: 8,
        coverage: 'single',
        subRows: [
          {
            aset: 'ice',
            jenis: 'things',
            kode: 19,
            tiang_gardist: 43,
            alamat: 83,
            coverage: 'single',
          },
          {
            aset: 'money',
            jenis: 'dad',
            kode: 28,
            tiang_gardist: 5,
            alamat: 13,
            coverage: 'single',
          },
          {
            aset: 'pencil',
            jenis: 'interest',
            kode: 2,
            tiang_gardist: 86,
            alamat: 92,
            coverage: 'complicated',
          },
          {
            aset: 'cast',
            jenis: 'road',
            kode: 25,
            tiang_gardist: 8,
            alamat: 42,
            coverage: 'complicated',
          },
          {
            aset: 'ice',
            jenis: 'dress',
            kode: 25,
            tiang_gardist: 86,
            alamat: 62,
            coverage: 'complicated',
          },
        ],
      },
      {
        aset: 'vest',
        jenis: 'team',
        kode: 22,
        tiang_gardist: 54,
        alamat: 47,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'clock',
            jenis: 'level',
            kode: 11,
            tiang_gardist: 33,
            alamat: 2,
            coverage: 'complicated',
          },
          {
            aset: 'passenger',
            jenis: 'act',
            kode: 9,
            tiang_gardist: 91,
            alamat: 89,
            coverage: 'complicated',
          },
          {
            aset: 'houses',
            jenis: 'flesh',
            kode: 27,
            tiang_gardist: 80,
            alamat: 25,
            coverage: 'complicated',
          },
          {
            aset: 'tray',
            jenis: 'cats',
            kode: 9,
            tiang_gardist: 42,
            alamat: 0,
            coverage: 'relationship',
          },
          {
            aset: 'tooth',
            jenis: 'map',
            kode: 19,
            tiang_gardist: 83,
            alamat: 29,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'trip',
        jenis: 'beef',
        kode: 10,
        tiang_gardist: 51,
        alamat: 82,
        coverage: 'single',
        subRows: [
          {
            aset: 'distribution',
            jenis: 'mark',
            kode: 25,
            tiang_gardist: 15,
            alamat: 6,
            coverage: 'complicated',
          },
          {
            aset: 'sneeze',
            jenis: 'monkey',
            kode: 20,
            tiang_gardist: 71,
            alamat: 96,
            coverage: 'complicated',
          },
          {
            aset: 'villkode',
            jenis: 'temper',
            kode: 17,
            tiang_gardist: 67,
            alamat: 55,
            coverage: 'single',
          },
          {
            aset: 'paper',
            jenis: 'note',
            kode: 12,
            tiang_gardist: 80,
            alamat: 89,
            coverage: 'relationship',
          },
          {
            aset: 'version',
            jenis: 'student',
            kode: 5,
            tiang_gardist: 3,
            alamat: 34,
            coverage: 'relationship',
          },
        ],
      },
    ],
  },
  {
    aset: 'accident',
    jenis: 'border',
    kode: 17,
    tiang_gardist: 24,
    alamat: 26,
    coverage: 'complicated',
    subRows: [
      {
        aset: 'distance',
        jenis: 'fish',
        kode: 23,
        tiang_gardist: 70,
        alamat: 91,
        coverage: 'single',
        subRows: [
          {
            aset: 'sheet',
            jenis: 'interest',
            kode: 12,
            tiang_gardist: 58,
            alamat: 81,
            coverage: 'single',
          },
          {
            aset: 'plastic',
            jenis: 'seashore',
            kode: 10,
            tiang_gardist: 3,
            alamat: 94,
            coverage: 'relationship',
          },
          {
            aset: 'bucket',
            jenis: 'love',
            kode: 4,
            tiang_gardist: 82,
            alamat: 99,
            coverage: 'complicated',
          },
          {
            aset: 'sound',
            jenis: 'poetry',
            kode: 18,
            tiang_gardist: 50,
            alamat: 7,
            coverage: 'complicated',
          },
          {
            aset: 'cream',
            jenis: 'ladybug',
            kode: 3,
            tiang_gardist: 48,
            alamat: 82,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'messkode',
        jenis: 'hotel',
        kode: 12,
        tiang_gardist: 96,
        alamat: 6,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'intention',
            jenis: 'wound',
            kode: 11,
            tiang_gardist: 81,
            alamat: 96,
            coverage: 'relationship',
          },
          {
            aset: 'store',
            jenis: 'version',
            kode: 9,
            tiang_gardist: 66,
            alamat: 32,
            coverage: 'relationship',
          },
          {
            aset: 'daughter',
            jenis: 'introduction',
            kode: 29,
            tiang_gardist: 20,
            alamat: 29,
            coverage: 'relationship',
          },
          {
            aset: 'association',
            jenis: 'silver',
            kode: 29,
            tiang_gardist: 18,
            alamat: 76,
            coverage: 'relationship',
          },
          {
            aset: 'enthusiasm',
            jenis: 'health',
            kode: 29,
            tiang_gardist: 62,
            alamat: 61,
            coverage: 'complicated',
          },
        ],
      },
      {
        aset: 'star',
        jenis: 'car',
        kode: 6,
        tiang_gardist: 6,
        alamat: 48,
        coverage: 'single',
        subRows: [
          {
            aset: 'cousin',
            jenis: 'sort',
            kode: 18,
            tiang_gardist: 39,
            alamat: 87,
            coverage: 'complicated',
          },
          {
            aset: 'driver',
            jenis: 'curve',
            kode: 2,
            tiang_gardist: 91,
            alamat: 40,
            coverage: 'single',
          },
          {
            aset: 'criticism',
            jenis: 'girl',
            kode: 11,
            tiang_gardist: 31,
            alamat: 34,
            coverage: 'complicated',
          },
          {
            aset: 'poet',
            jenis: 'instruction',
            kode: 8,
            tiang_gardist: 6,
            alamat: 53,
            coverage: 'relationship',
          },
          {
            aset: 'analyst',
            jenis: 'jump',
            kode: 14,
            tiang_gardist: 75,
            alamat: 13,
            coverage: 'single',
          },
        ],
      },
      {
        aset: 'seat',
        jenis: 'able',
        kode: 21,
        tiang_gardist: 46,
        alamat: 67,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'babies',
            jenis: 'teacher',
            kode: 6,
            tiang_gardist: 70,
            alamat: 9,
            coverage: 'relationship',
          },
          {
            aset: 'software',
            jenis: 'list',
            kode: 21,
            tiang_gardist: 65,
            alamat: 43,
            coverage: 'relationship',
          },
          {
            aset: 'sympathy',
            jenis: 'presentation',
            kode: 18,
            tiang_gardist: 50,
            alamat: 10,
            coverage: 'single',
          },
          {
            aset: 'yam',
            jenis: 'college',
            kode: 22,
            tiang_gardist: 66,
            alamat: 77,
            coverage: 'single',
          },
          {
            aset: 'field',
            jenis: 'department',
            kode: 11,
            tiang_gardist: 98,
            alamat: 41,
            coverage: 'single',
          },
        ],
      },
      {
        aset: 'safety',
        jenis: 'dad',
        kode: 20,
        tiang_gardist: 15,
        alamat: 1,
        coverage: 'relationship',
        subRows: [
          {
            aset: 'sofa',
            jenis: 'fuel',
            kode: 28,
            tiang_gardist: 70,
            alamat: 7,
            coverage: 'complicated',
          },
          {
            aset: 'flower',
            jenis: 'stocking',
            kode: 0,
            tiang_gardist: 99,
            alamat: 31,
            coverage: 'relationship',
          },
          {
            aset: 'airplane',
            jenis: 'steel',
            kode: 18,
            tiang_gardist: 83,
            alamat: 68,
            coverage: 'single',
          },
          {
            aset: 'train',
            jenis: 'rail',
            kode: 21,
            tiang_gardist: 89,
            alamat: 95,
            coverage: 'complicated',
          },
          {
            aset: 'feast',
            jenis: 'signature',
            kode: 4,
            tiang_gardist: 44,
            alamat: 31,
            coverage: 'complicated',
          },
        ],
      },
    ],
  },
  {
    aset: 'love',
    jenis: 'range',
    kode: 10,
    tiang_gardist: 84,
    alamat: 98,
    coverage: 'relationship',
    subRows: [
      {
        aset: 'winner',
        jenis: 'security',
        kode: 6,
        tiang_gardist: 51,
        alamat: 32,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'definition',
            jenis: 'revenue',
            kode: 4,
            tiang_gardist: 52,
            alamat: 53,
            coverage: 'single',
          },
          {
            aset: 'possibility',
            jenis: 'talk',
            kode: 19,
            tiang_gardist: 97,
            alamat: 43,
            coverage: 'complicated',
          },
          {
            aset: 'photo',
            jenis: 'tank',
            kode: 16,
            tiang_gardist: 5,
            alamat: 99,
            coverage: 'single',
          },
          {
            aset: 'iron',
            jenis: 'drink',
            kode: 10,
            tiang_gardist: 64,
            alamat: 0,
            coverage: 'single',
          },
          {
            aset: 'net',
            jenis: 'mint',
            kode: 9,
            tiang_gardist: 44,
            alamat: 51,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'balance',
        jenis: 'design',
        kode: 21,
        tiang_gardist: 32,
        alamat: 82,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'thumb',
            jenis: 'bottle',
            kode: 20,
            tiang_gardist: 84,
            alamat: 62,
            coverage: 'single',
          },
          {
            aset: 'boundary',
            jenis: 'chess',
            kode: 4,
            tiang_gardist: 37,
            alamat: 69,
            coverage: 'single',
          },
          {
            aset: 'significance',
            jenis: 'end',
            kode: 5,
            tiang_gardist: 25,
            alamat: 95,
            coverage: 'relationship',
          },
          {
            aset: 'breakfast',
            jenis: 'magazine',
            kode: 2,
            tiang_gardist: 66,
            alamat: 7,
            coverage: 'complicated',
          },
          {
            aset: 'midnight',
            jenis: 'disk',
            kode: 23,
            tiang_gardist: 91,
            alamat: 44,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'kick',
        jenis: 'sticks',
        kode: 11,
        tiang_gardist: 97,
        alamat: 19,
        coverage: 'single',
        subRows: [
          {
            aset: 'shoes',
            jenis: 'variation',
            kode: 20,
            tiang_gardist: 21,
            alamat: 84,
            coverage: 'single',
          },
          {
            aset: 'hair',
            jenis: 'yard',
            kode: 25,
            tiang_gardist: 2,
            alamat: 42,
            coverage: 'complicated',
          },
          {
            aset: 'turkey',
            jenis: 'sort',
            kode: 0,
            tiang_gardist: 69,
            alamat: 60,
            coverage: 'relationship',
          },
          {
            aset: 'place',
            jenis: 'cushion',
            kode: 15,
            tiang_gardist: 5,
            alamat: 9,
            coverage: 'relationship',
          },
          {
            aset: 'tomatoes',
            jenis: 'definition',
            kode: 3,
            tiang_gardist: 26,
            alamat: 19,
            coverage: 'complicated',
          },
        ],
      },
      {
        aset: 'squirrel',
        jenis: 'langukode',
        kode: 23,
        tiang_gardist: 42,
        alamat: 24,
        coverage: 'relationship',
        subRows: [
          {
            aset: 'head',
            jenis: 'edge',
            kode: 3,
            tiang_gardist: 80,
            alamat: 58,
            coverage: 'complicated',
          },
          {
            aset: 'stop',
            jenis: 'basket',
            kode: 18,
            tiang_gardist: 29,
            alamat: 85,
            coverage: 'single',
          },
          {
            aset: 'apple',
            jenis: 'music',
            kode: 27,
            tiang_gardist: 97,
            alamat: 82,
            coverage: 'complicated',
          },
          {
            aset: 'mind',
            jenis: 'fruit',
            kode: 0,
            tiang_gardist: 66,
            alamat: 53,
            coverage: 'relationship',
          },
          {
            aset: 'orange',
            jenis: 'medicine',
            kode: 3,
            tiang_gardist: 98,
            alamat: 13,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'error',
        jenis: 'map',
        kode: 26,
        tiang_gardist: 29,
        alamat: 9,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'reality',
            jenis: 'aspect',
            kode: 8,
            tiang_gardist: 85,
            alamat: 41,
            coverage: 'complicated',
          },
          {
            aset: 'establishment',
            jenis: 'republic',
            kode: 18,
            tiang_gardist: 2,
            alamat: 21,
            coverage: 'relationship',
          },
          {
            aset: 'crow',
            jenis: 'refrigerator',
            kode: 12,
            tiang_gardist: 49,
            alamat: 96,
            coverage: 'relationship',
          },
          {
            aset: 'cork',
            jenis: 'activity',
            kode: 29,
            tiang_gardist: 46,
            alamat: 49,
            coverage: 'single',
          },
          {
            aset: 'recognition',
            jenis: 'houses',
            kode: 7,
            tiang_gardist: 37,
            alamat: 40,
            coverage: 'single',
          },
        ],
      },
    ],
  },
  {
    aset: 'department',
    jenis: 'procedure',
    kode: 28,
    tiang_gardist: 68,
    alamat: 83,
    coverage: 'complicated',
    subRows: [
      {
        aset: 'territory',
        jenis: 'complaint',
        kode: 7,
        tiang_gardist: 11,
        alamat: 13,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'emotion',
            jenis: 'vacation',
            kode: 19,
            tiang_gardist: 1,
            alamat: 48,
            coverage: 'complicated',
          },
          {
            aset: 'bulb',
            jenis: 'assistant',
            kode: 3,
            tiang_gardist: 99,
            alamat: 66,
            coverage: 'relationship',
          },
          {
            aset: 'volcano',
            jenis: 'low',
            kode: 24,
            tiang_gardist: 12,
            alamat: 7,
            coverage: 'single',
          },
          {
            aset: 'length',
            jenis: 'jellyfish',
            kode: 1,
            tiang_gardist: 79,
            alamat: 2,
            coverage: 'relationship',
          },
          {
            aset: 'quantity',
            jenis: 'channel',
            kode: 1,
            tiang_gardist: 6,
            alamat: 64,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'location',
        jenis: 'priority',
        kode: 16,
        tiang_gardist: 45,
        alamat: 4,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'inspection',
            jenis: 'whip',
            kode: 14,
            tiang_gardist: 23,
            alamat: 61,
            coverage: 'relationship',
          },
          {
            aset: 'acoustics',
            jenis: 'cats',
            kode: 21,
            tiang_gardist: 96,
            alamat: 0,
            coverage: 'complicated',
          },
          {
            aset: 'foundation',
            jenis: 'reason',
            kode: 19,
            tiang_gardist: 32,
            alamat: 36,
            coverage: 'complicated',
          },
          {
            aset: 'community',
            jenis: 'decision',
            kode: 27,
            tiang_gardist: 67,
            alamat: 78,
            coverage: 'relationship',
          },
          {
            aset: 'committee',
            jenis: 'rabbits',
            kode: 2,
            tiang_gardist: 68,
            alamat: 5,
            coverage: 'single',
          },
        ],
      },
      {
        aset: 'drawing',
        jenis: 'clock',
        kode: 17,
        tiang_gardist: 63,
        alamat: 96,
        coverage: 'relationship',
        subRows: [
          {
            aset: 'context',
            jenis: 'winter',
            kode: 5,
            tiang_gardist: 97,
            alamat: 5,
            coverage: 'single',
          },
          {
            aset: 'effort',
            jenis: 'glove',
            kode: 4,
            tiang_gardist: 83,
            alamat: 6,
            coverage: 'relationship',
          },
          {
            aset: 'virus',
            jenis: 'candidate',
            kode: 24,
            tiang_gardist: 48,
            alamat: 13,
            coverage: 'complicated',
          },
          {
            aset: 'visitor',
            jenis: 'speaker',
            kode: 17,
            tiang_gardist: 11,
            alamat: 51,
            coverage: 'complicated',
          },
          {
            aset: 'talk',
            jenis: 'act',
            kode: 8,
            tiang_gardist: 44,
            alamat: 2,
            coverage: 'single',
          },
        ],
      },
      {
        aset: 'visitor',
        jenis: 'studio',
        kode: 24,
        tiang_gardist: 88,
        alamat: 0,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'computer',
            jenis: 'stretch',
            kode: 25,
            tiang_gardist: 31,
            alamat: 3,
            coverage: 'relationship',
          },
          {
            aset: 'description',
            jenis: 'liquid',
            kode: 1,
            tiang_gardist: 64,
            alamat: 2,
            coverage: 'single',
          },
          {
            aset: 'mitten',
            jenis: 'knee',
            kode: 11,
            tiang_gardist: 94,
            alamat: 11,
            coverage: 'relationship',
          },
          {
            aset: 'vehicle',
            jenis: 'playground',
            kode: 15,
            tiang_gardist: 50,
            alamat: 17,
            coverage: 'relationship',
          },
          {
            aset: 'cookie',
            jenis: 'toothpaste',
            kode: 14,
            tiang_gardist: 74,
            alamat: 34,
            coverage: 'single',
          },
        ],
      },
      {
        aset: 'roll',
        jenis: 'tank',
        kode: 25,
        tiang_gardist: 50,
        alamat: 21,
        coverage: 'single',
        subRows: [
          {
            aset: 'stick',
            jenis: 'oatmeal',
            kode: 26,
            tiang_gardist: 32,
            alamat: 19,
            coverage: 'complicated',
          },
          {
            aset: 'wife',
            jenis: 'growth',
            kode: 7,
            tiang_gardist: 37,
            alamat: 97,
            coverage: 'relationship',
          },
          {
            aset: 'bear',
            jenis: 'emphasis',
            kode: 16,
            tiang_gardist: 8,
            alamat: 51,
            coverage: 'relationship',
          },
          {
            aset: 'lumber',
            jenis: 'method',
            kode: 0,
            tiang_gardist: 67,
            alamat: 20,
            coverage: 'relationship',
          },
          {
            aset: 'attention',
            jenis: 'clover',
            kode: 27,
            tiang_gardist: 95,
            alamat: 52,
            coverage: 'single',
          },
        ],
      },
    ],
  },
  {
    aset: 'voice',
    jenis: 'beer',
    kode: 14,
    tiang_gardist: 45,
    alamat: 93,
    coverage: 'single',
    subRows: [
      {
        aset: 'sheep',
        jenis: 'drain',
        kode: 22,
        tiang_gardist: 33,
        alamat: 27,
        coverage: 'single',
        subRows: [
          {
            aset: 'alarm',
            jenis: 'detail',
            kode: 12,
            tiang_gardist: 38,
            alamat: 73,
            coverage: 'relationship',
          },
          {
            aset: 'loss',
            jenis: 'furniture',
            kode: 11,
            tiang_gardist: 89,
            alamat: 41,
            coverage: 'single',
          },
          {
            aset: 'information',
            jenis: 'patience',
            kode: 10,
            tiang_gardist: 18,
            alamat: 2,
            coverage: 'complicated',
          },
          {
            aset: 'game',
            jenis: 'cough',
            kode: 16,
            tiang_gardist: 11,
            alamat: 91,
            coverage: 'relationship',
          },
          {
            aset: 'body',
            jenis: 'lady',
            kode: 5,
            tiang_gardist: 67,
            alamat: 65,
            coverage: 'complicated',
          },
        ],
      },
      {
        aset: 'street',
        jenis: 'yam',
        kode: 25,
        tiang_gardist: 93,
        alamat: 58,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'difficulty',
            jenis: 'religion',
            kode: 7,
            tiang_gardist: 86,
            alamat: 64,
            coverage: 'relationship',
          },
          {
            aset: 'coal',
            jenis: 'philosophy',
            kode: 0,
            tiang_gardist: 47,
            alamat: 87,
            coverage: 'single',
          },
          {
            aset: 'youth',
            jenis: 'friendship',
            kode: 8,
            tiang_gardist: 68,
            alamat: 0,
            coverage: 'relationship',
          },
          {
            aset: 'responsibility',
            jenis: 'product',
            kode: 28,
            tiang_gardist: 94,
            alamat: 74,
            coverage: 'complicated',
          },
          {
            aset: 'crib',
            jenis: 'blade',
            kode: 7,
            tiang_gardist: 90,
            alamat: 66,
            coverage: 'relationship',
          },
        ],
      },
      {
        aset: 'recess',
        jenis: 'plane',
        kode: 12,
        tiang_gardist: 38,
        alamat: 41,
        coverage: 'complicated',
        subRows: [
          {
            aset: 'governor',
            jenis: 'obligation',
            kode: 29,
            tiang_gardist: 14,
            alamat: 29,
            coverage: 'complicated',
          },
          {
            aset: 'angle',
            jenis: 'back',
            kode: 17,
            tiang_gardist: 60,
            alamat: 54,
            coverage: 'single',
          },
          {
            aset: 'dust',
            jenis: 'condition',
            kode: 14,
            tiang_gardist: 44,
            alamat: 35,
            coverage: 'relationship',
          },
          {
            aset: 'giants',
            jenis: 'camera',
            kode: 19,
            tiang_gardist: 27,
            alamat: 28,
            coverage: 'relationship',
          },
          {
            aset: 'cellar',
            jenis: 'jam',
            kode: 14,
            tiang_gardist: 86,
            alamat: 48,
            coverage: 'complicated',
          },
        ],
      },
      {
        aset: 'summer',
        jenis: 'consequence',
        kode: 25,
        tiang_gardist: 8,
        alamat: 7,
        coverage: 'relationship',
        subRows: [
          {
            aset: 'sand',
            jenis: 'waves',
            kode: 12,
            tiang_gardist: 31,
            alamat: 51,
            coverage: 'relationship',
          },
          {
            aset: 'kitty',
            jenis: 'session',
            kode: 13,
            tiang_gardist: 98,
            alamat: 21,
            coverage: 'relationship',
          },
          {
            aset: 'wilderness',
            jenis: 'team',
            kode: 14,
            tiang_gardist: 31,
            alamat: 78,
            coverage: 'complicated',
          },
          {
            aset: 'health',
            jenis: 'category',
            kode: 1,
            tiang_gardist: 62,
            alamat: 22,
            coverage: 'single',
          },
          {
            aset: 'gun',
            jenis: 'performance',
            kode: 11,
            tiang_gardist: 9,
            alamat: 22,
            coverage: 'single',
          },
        ],
      },
      {
        aset: 'garden',
        jenis: 'popcorn',
        kode: 16,
        tiang_gardist: 23,
        alamat: 11,
        coverage: 'relationship',
        subRows: [
          {
            aset: 'chairs',
            jenis: 'flavor',
            kode: 26,
            tiang_gardist: 81,
            alamat: 81,
            coverage: 'single',
          },
          {
            aset: 'sky',
            jenis: 'lace',
            kode: 24,
            tiang_gardist: 94,
            alamat: 20,
            coverage: 'single',
          },
          {
            aset: 'water',
            jenis: 'power',
            kode: 6,
            tiang_gardist: 75,
            alamat: 14,
            coverage: 'complicated',
          },
          {
            aset: 'article',
            jenis: 'root',
            kode: 20,
            tiang_gardist: 53,
            alamat: 99,
            coverage: 'single',
          },
          {
            aset: 'ink',
            jenis: 'library',
            kode: 5,
            tiang_gardist: 85,
            alamat: 71,
            coverage: 'single',
          },
        ],
      },
    ],
  },
];
