import { IJaringan } from "./jaringan-lokasi.interface";

interface IJaringanZone {
  number: number,
  id: number,
  nama_lokasi: string,
  kode_lokasi: string;
  alamat: string,
  parent_lokasi: any,
  status_listrik: TJaringan,
  tree_jaringan: TJaringan,
  status_penyulang: string,
  coverage: string,
  kva: string,
  phase: string,
  jenis: number,
  jenis_jaringan: any,
  lat: number,
  lon: number,
  count_gardu: number,
  gardu_hubung: IJaringan,
  penyulang: IJaringan,
  id_gardu_hubung: any,
  id_penyulang: any,
  id_parent_lokasi: any,
  id_ref_jenis_lokasi: any,
  id_user_entri: any;
  id_user_update: any;
  gardu_induk: IJaringan,
  uid: IJaringan,
  up3_1: IJaringan,
  ulp_1: IJaringan,
  tgl_entri: any,
  tgl_update: any,
  panjang_jaringan: any,
  zona: any,
  jumlah_pelanggan: any,
  sinkron_data: any,
  id_i: any,
  id_v: any,
  id_p: any,
  id_amr: any,
  id_portal_ext: any,
  url_webservice: any,
  jenis_peralatan: any,
  fungsi_lokasi: any,
  pemilik: any,
  i_max: any,
  path1: any,
  path2: any,
  path3: any,
  rekon_beban: TJaringan,
}

export const JaringanZoneField = {
  id_ref_lokasi: null,
  path1: null,
  path2: null,
  path3: null,
  id_ref_jenis_lokasi: null,
  id_parent_lokasi: null,
  id_gardu_hubung: null,
  id_trafo_gi: null,
  id_penyulang: null,
  trafo_gi: null,
  nama_lokasi: '',
  kode_lokasi: '',
  alamat: '',
  // lat: 0,
  // lon: 0,
  // coverage: 0,
  // kva: 0,
  zona: null,
  jenis_peralatan: '',
  id_user_entri: '',
  id_user_update: '',
  jenis_jaringan: null,
  status_listrik: '1',
  status_penyulang: null,
  panjang_jaringan: 0,
  id_uid: null,
  id_up3_1: null,
  id_ulp_1: null,
  sinkron_data: null,
  id_i: null,
  id_v: null,
  id_p: null,
  id_amr: null,
  id_portal_ext: null,
  url_webservice: null,
  fungsi_lokasi: null,
  pemilik: null,
  jumlah_pelanggan: 0,
  i_max: null,
  rekon_beban: '1',
}

type TJaringan = 1 | 0;
// type TRekonBeban = 1 | 0;

export type { IJaringanZone };
