interface IInputJadwal {
  nama_lokasi:string,
  id_trans_ep_peralatan: null,
  jenis_peralatan:string,
  tgl_entri: string,
  tgl_open: string,
  tgl_close: string,
  status_rc_open: string,
  status_rc_close: string,
  peralatan: string,
  peralatan_rc: string,
  lbs_manual: string,
  id_peralatan: number,
  beban: string,
  beban_masuk: string,
  section: string,
  waktu_masuk: string,
  rc_close: string,
  rc_open: string,
  status_operasi:string,
  r:string,
  s:string,
  t:string,
  n:string,
  keterangan:string,
  // status_manuver: null,
}
export const OpsisPeralatanRCFeild = {
  r:null,
  s:null,
  t:null,
  n:null,
  keterangan:null,
  status_operasi:null,
  nama_lokasi:null,
  jenis_peralatan:null,
  id_trans_ep_peralatan: null,
  id_ref_ep_ag_hmi: null,
  tgl_entri: null,
  tgl_open: null,
  tgl_close: null,
  status_rc_open: null,
  status_rc_close: null,
  peralatan: null,
  peralatan_rc: null,
  lbs_manual: null,
  id_peralatan: null,
  beban: null,
  beban_masuk: null,
  section: null,
  waktu_masuk: null,
  rc_close: null,
  rc_open: null,
  // status_manuver: null,
};

export type { IInputJadwal };