interface IWpSOPnJSA {
  judul_pekerjaan: string;
  nomor: string;
  nama_file: string;
  langkah1: string;
  langkah2: string;
  langkah3: string;
  langkah4: string;
  langkah5: string;
  langkah6: string;
  langkah7: string;
  langkah8: string;
  langkah9: string;
  langkah10: string;
  langkah11: string;
  langkah12: string;
  langkah13: string;
  langkah14: string;
  langkah15: string;
  potensi1: string;
  potensi2: string;
  potensi3: string;
  potensi4: string;
  potensi5: string;
  potensi6: string;
  potensi7: string;
  potensi8: string;
  potensi9: string;
  potensi10: string;
  potensi11: string;
  potensi12: string;
  potensi13: string;
  potensi14: string;
  potensi15: string;
  pengendalian1: string;
  pengendalian2: string;
  pengendalian3: string;
  pengendalian4: string;
  pengendalian5: string;
  pengendalian6: string;
  pengendalian7: string;
  pengendalian8: string;
  pengendalian9: string;
  pengendalian10: string;
  pengendalian11: string;
  pengendalian12: string;
  pengendalian13: string;
  pengendalian14: string;
  pengendalian15: string;
  tgl_entri:string;
  tgl_update:string;
  id_wp_master_bagian: any;
}

export const WpSOPnJSAField = {
  judul_pekerjaan: '',
  nomor: '',
  nama_file: '',
  langkah1: '',
  langkah2: '',
  langkah3: '',
  langkah4: '',
  langkah5: '',
  langkah6: '',
  langkah7: '',
  langkah8: '',
  langkah9: '',
  langkah10: '',
  langkah11: '',
  langkah12: '',
  langkah13: '',
  langkah14: '',
  langkah15: '',
  potensi1: '',
  potensi2: '',
  potensi3: '',
  potensi4: '',
  potensi5: '',
  potensi6: '',
  potensi7: '',
  potensi8: '',
  potensi9: '',
  potensi10: '',
  potensi11: '',
  potensi12: '',
  potensi13: '',
  potensi14: '',
  potensi15: '',
  pengendalian1: '',
  pengendalian2: '',
  pengendalian3: '',
  pengendalian4: '',
  pengendalian5: '',
  pengendalian6: '',
  pengendalian7: '',
  pengendalian8: '',
  pengendalian9: '',
  pengendalian10: '',
  pengendalian11: '',
  pengendalian12: '',
  pengendalian13: '',
  pengendalian14: '',
  pengendalian15: '',
  id_wp_master_bagian: undefined,
  id_wp_master_sop_jsa: undefined,
};
export type { IWpSOPnJSA };
